/*Given the CITY and COUNTRY tables, query the sum of the 
populations of all cities where the CONTINENT is 'Asia'.
Note: CITY.CountryCode and COUNTRY.Code are matching key columns.

CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION)
COUNTRY(CODE,NAME,CONTINENT,REGION,SURFACEAREA,POPULATION,
LIFEEXPECTANCY,GNP,GNPOLD,LOCALNAME,GOVERNMENTFORM,
HEADOFSTATE,CAPITAL, CODE2)*/

SELECT SUM(CITY.POPULATION) 
FROM CITY
JOIN COUNTRY 
ON CITY.CountryCode = COUNTRY.Code
WHERE COUNTRY.CONTINENT = 'Asia'
GROUP BY COUNTRY.CONTINENT;