/*Given the CITY and COUNTRY tables, query the names of all 
cities where the CONTINENT is 'Africa'.
Note: CITY.CountryCode and COUNTRY.Code are matching key columns.
CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION)
COUNTRY(CODE,NAME,CONTINENT,REGION,SURFACEAREA,POPULATION,
LIFEEXPECTANCY,GNP,GNPOLD,LOCALNAME,GOVERNMENTFORM,
HEADOFSTATE,CAPITAL, CODE2)*/

SELECT CITY.NAME
FROM CITY
JOIN COUNTRY
ON CITY.COUNTRYCODE = COUNTRY.Code
WHERE CONTINENT = 'Africa';