/*Query the sum of the populations for all Japanese cities in 
CITY. The COUNTRYCODE for Japan is JPN.

CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION)*/

SELECT SUM(POPULATION)
FROM CITY
WHERE COUNTRYCODE = 'JPN';